//! Emit the per-schema plugin `lib.rs`: a C-ABI surface plus a `walk_*` function
//! per kaitai type that turns the typed, kaitai-generated struct into a generic
//! [`kdiff_abi::Node`] tree. Driven entirely by the resolved [`Schema`].

use crate::model::{Kind, Schema, WField};
use crate::rustkw::esc_ident;
use std::fmt::Write;

/// Generate the complete `src/lib.rs` for a plugin crate.
pub fn generate_lib_rs(schema: &Schema) -> String {
    let mut s = String::new();
    let root = &schema.root_rust;

    s.push_str(
        "// GENERATED by kdiff. Do not edit.\n\
         #![allow(non_snake_case, non_camel_case_types, dead_code, unused_imports, unused_variables)]\n\n\
         use kaitai::*;\n\
         use kdiff_abi::{Field, Node, ParseResult};\n\n\
         mod schema;\n\
         use schema::*;\n\n",
    );

    for ty in &schema.types {
        emit_walker(&mut s, &ty.rust_name, &ty.fields);
    }

    let _ = write!(
        s,
        "\n#[no_mangle]\npub extern \"C\" fn kdiff_abi_version() -> u32 {{ kdiff_abi::ABI_VERSION }}\n\n\
         fn parse(bytes: Vec<u8>) -> ParseResult {{\n\
         \x20   let reader = BytesReader::from(bytes);\n\
         \x20   match {root}::read_into::<BytesReader, {root}>(&reader, None, None) {{\n\
         \x20       Ok(o) => ParseResult::Ok(walk_{root}(&o)),\n\
         \x20       Err(e) => ParseResult::Err(format!(\"{{e:?}}\")),\n\
         \x20   }}\n}}\n\n",
        root = root
    );

    s.push_str(FFI_BOILERPLATE);
    s
}

fn emit_walker(s: &mut String, ty: &str, fields: &[WField]) {
    let _ = write!(s, "fn walk_{ty}(o: &{ty}) -> Node {{\n    let mut f: Vec<Field> = Vec::new();\n");
    for field in fields {
        let expr = field_expr(field);
        let _ = write!(s, "    f.push(Field::new({:?}, {}));\n", field.id, expr);
    }
    let _ = write!(s, "    Node::Struct {{ ty: {ty:?}.to_string(), fields: f }}\n}}\n\n");
}

/// The expression producing the `Node` for one field.
fn field_expr(field: &WField) -> String {
    let id = &field.id;
    if field.repeat {
        // getter -> Ref<Vec<Elem>>; iterate and map each element.
        let g = esc_ident(id);
        let (list_ty, per_elem) = repeat_elem(&field.kind, "it");
        format!(
            "{{ let xs = o.{g}(); let mut v: Vec<Node> = Vec::new(); \
             for it in xs.iter() {{ v.push({per_elem}); }} \
             Node::List {{ ty: {list_ty:?}.to_string(), items: v }} }}"
        )
    } else {
        scalar_expr(&field.kind, id)
    }
}

/// Expression for a non-repeated field, calling getter `o.<id>()`.
fn scalar_expr(kind: &Kind, id: &str) -> String {
    let g = esc_ident(id); // getter name, escaped for Rust keywords
    match kind {
        Kind::UInt => format!("Node::uint(*o.{g}())"),
        Kind::Int => format!("Node::int(*o.{g}())"),
        Kind::Float => format!("Node::float(*o.{g}() as f64)"),
        Kind::Str => format!("Node::Str(o.{g}().clone())"),
        Kind::Bytes => format!("Node::Bytes(o.{g}().clone())"),
        Kind::Enum { rust_name } => format!(
            "Node::enom({rust_name:?}, format!(\"{{:?}}\", *o.{g}()), i64::from(&*o.{g}()))"
        ),
        Kind::User { rust_name } => format!(
            "{{ let v = o.{g}(); if v.is_none() {{ Node::Null }} else {{ walk_{rust_name}(&v) }} }}"
        ),
        Kind::Switch { enum_name, variants } => {
            let mut arms = String::new();
            for v in variants {
                let _ = write!(
                    arms,
                    "Some({enum_name}::{variant}(x)) => walk_{case}(x), ",
                    variant = v.variant,
                    case = v.case_rust
                );
            }
            format!(
                "match &*o.{g}() {{ {arms}None => Node::Null, \
                 #[allow(unreachable_patterns)] _ => Node::Null }}"
            )
        }
    }
}

/// For a repeated field, returns `(list_type_label, per_element_expr)` where the
/// element is bound as `var` (type `&Elem`).
fn repeat_elem(kind: &Kind, var: &str) -> (String, String) {
    match kind {
        Kind::UInt => ("uint".to_string(), format!("Node::uint(*{var})")),
        Kind::Int => ("int".to_string(), format!("Node::int(*{var})")),
        Kind::Float => ("float".to_string(), format!("Node::float(*{var} as f64)")),
        Kind::Str => ("str".to_string(), format!("Node::Str({var}.clone())")),
        Kind::Bytes => ("bytes".to_string(), format!("Node::Bytes({var}.clone())")),
        Kind::Enum { rust_name } => (
            rust_name.clone(),
            format!("Node::enom({rust_name:?}, format!(\"{{:?}}\", *{var}), i64::from({var}))"),
        ),
        Kind::User { rust_name } => (rust_name.clone(), format!("walk_{rust_name}({var})")),
        Kind::Switch { enum_name, variants } => {
            let mut arms = String::new();
            for v in variants {
                let _ = write!(
                    arms,
                    "Some({enum_name}::{variant}(x)) => walk_{case}(x), ",
                    variant = v.variant,
                    case = v.case_rust
                );
            }
            (
                enum_name.clone(),
                format!(
                    "match {var} {{ {arms}None => Node::Null, \
                     #[allow(unreachable_patterns)] _ => Node::Null }}"
                ),
            )
        }
    }
}

const FFI_BOILERPLATE: &str = r#"#[no_mangle]
pub extern "C" fn kdiff_parse(ptr: *const u8, len: usize, out_len: *mut usize) -> *mut u8 {
    let bytes = if ptr.is_null() { Vec::new() } else {
        unsafe { std::slice::from_raw_parts(ptr, len) }.to_vec()
    };
    let result = std::panic::catch_unwind(move || parse(bytes))
        .unwrap_or_else(|_| ParseResult::Err("panic while parsing".to_string()));
    let json = result.to_json_bytes().into_boxed_slice();
    unsafe { *out_len = json.len(); }
    Box::into_raw(json) as *mut u8
}

#[no_mangle]
pub extern "C" fn kdiff_free(ptr: *mut u8, len: usize) {
    if ptr.is_null() { return; }
    unsafe {
        let slice = std::slice::from_raw_parts_mut(ptr, len);
        drop(Box::from_raw(slice as *mut [u8]));
    }
}
"#;
